server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Astro com trailingSlash: 'always' e format: directory
    location / {
        try_files $uri $uri/ $uri/index.html =404;
    }

    # Cache leve pra assets estáticos do build
    location /_astro/ {
        expires 7d;
        add_header Cache-Control "public";
        try_files $uri =404;
    }

    location /assets/ {
        expires 7d;
        add_header Cache-Control "public";
        try_files $uri =404;
    }

    gzip on;
    gzip_types text/css application/javascript application/json image/svg+xml;
}
